# Entropy Neurons

## Theoretical Justification

### Shifting Logits doesn't Effect Softmax Probabilites

The central point of an entropy neuron is that its outputs don't directly impact the probability distribution over the next words through the logits, i.e. change the logits in such a way the softmax in uneffected.  

What type of change doesn't effect the softmax? To my knowledge either trivially the indentity function and any type of shift.

In [2]:
# import libraries
import math
import numpy as np
import torch

def softmax(x):
    # put all the logits -> e^x
    exponentials = [torch.exp(i) for i in x]
    # need everything in a tensor not a list
    exponentials = torch.tensor(np.array(exponentials))
    # sum over all the exponentials to get normalizing factor
    sum = torch.sum(exponentials)
    return exponentials / sum

Let us create a random vector $\mathbf{x} \in [-10, 10]^{10}$ that represents our logits and see how shifts effect the logits:

In [9]:
x = (torch.rand(10) - 0.5) * 20
probabilities = softmax(x)
print(probabilities)

print("--------------------------------")

# shift the logits by some random constant
x_shifted = x + ( ( torch.rand(1) - 0.5 ) * 10 )
shifted_probabilities = softmax(x_shifted)
print(shifted_probabilities)



tensor([1.5163e-04, 4.0285e-03, 2.1082e-03, 1.7030e-07, 3.4375e-06, 2.9502e-07,
        5.0992e-04, 2.3387e-01, 2.5420e-03, 7.5678e-01])
--------------------------------
tensor([1.5163e-04, 4.0285e-03, 2.1082e-03, 1.7030e-07, 3.4375e-06, 2.9502e-07,
        5.0992e-04, 2.3387e-01, 2.5420e-03, 7.5678e-01])


Notice the two tensors are exactly the same!

### What are Entropy Neurons Doing then?

In [15]:
# import libraries
import math
import numpy as np
import torch

def softmax(x):
    # put all the logits -> e^x
    exponentials = [torch.exp(i) for i in x]
    # need everything in a tensor not a list
    exponentials = torch.tensor(np.array(exponentials))
    # sum over all the exponentials to get normalizing factor
    sum = torch.sum(exponentials)
    return exponentials / sum

def RMS(x):
    sum = 0
    for i in x:
        sum += i ** 2
    sum /= len(x)
    sum += 1e-9
    sum = math.sqrt(sum)
    return x / sum

Towards the end of the network we typically have a W_out matrix (last linear transformation matrix in last transformer block), followed by a Layer Norm (or RMSNorm), then a W_u matrix (unembedding matrix that projects to the vocabulary space, which are considered the logits) and finally the softmax.  

For some latent variable $x$ and some normilzation function $\phi$, say RMSNorm, the process before the softmax looks like:

$ W_u \phi(W_{out} x)$

Since $\phi$ is only scaling up or down the matrix the columns preserve their geometry (span, direction). We can then look at the effect each column has on $W_u$, i.e. look at it like this (c is some constant)

$ \frac{1}{c} (W_u W_{out}) x$

Sclaing the logits effects the entropy of the probabilites like changing tempature, here we can see $c$ doing this. Next, notice a column in the output of $W_u W_{out}$ is the linear combination of the columns $W_u$ weighted by a column of $W_{out}$. Then the result is the weighted sum (by $x$) of these outputs scaled by $c$.

An Entropy Neuron is a column in $W_{out}$ that shifts the result (which doesn't effect the probabilites) but effects the constant $c$ (which effectivly acts as changing the tempature).

Lets see an example of this happening in action:

In [14]:
# create a random matrix for W_out
w_out = (torch.rand((5,9)) )
# create a random matrix W_u
U = ( torch.rand((9,5)) ) 
# create a random latent variable for x
x = torch.rand(9)

""" We need a column of W_out matrix muliplication with W_u to output some constant vector 
so Im setting the first column of W_out to the first column of the identity matrix [1,0,0,...]
and the first column in W_u to the all ones vector. That way W_u W_out[0] = [1,1,1,1...]
""" 
print("Matrix W_out:")
w_out.T[0] = torch.zeros(5)
w_out[0][0] = torch.ones(1)
print(w_out)

print("\n--------------------------------\n")

print("Matrix W_u:")
U.T[0] = torch.ones(9) 
print(U)

Matrix W_out:
tensor([[1.0000, 0.0898, 0.3207, 0.3449, 0.3896, 0.4258, 0.3371, 0.6110, 0.3900],
        [0.0000, 0.6011, 0.3755, 0.7325, 0.4722, 0.3108, 0.8805, 0.0982, 0.4211],
        [0.0000, 0.2973, 0.6254, 0.8755, 0.2263, 0.2337, 0.8550, 0.8093, 0.9505],
        [0.0000, 0.3735, 0.8097, 0.1179, 0.9825, 0.1110, 0.2469, 0.6727, 0.8068],
        [0.0000, 0.7825, 0.9467, 0.7585, 0.3862, 0.1918, 0.3911, 0.7045, 0.8367]])

--------------------------------

Matrix W_u:
tensor([[1.0000, 0.2615, 0.2943, 0.2382, 0.6576],
        [1.0000, 0.7955, 0.0372, 0.1051, 0.0269],
        [1.0000, 0.0387, 0.0825, 0.8664, 0.3963],
        [1.0000, 0.8342, 0.7089, 0.6747, 0.3490],
        [1.0000, 0.9693, 0.0665, 0.5744, 0.2680],
        [1.0000, 0.2516, 0.7671, 0.3508, 0.2875],
        [1.0000, 0.8220, 0.3550, 0.2366, 0.4885],
        [1.0000, 0.7759, 0.6037, 0.9892, 0.2894],
        [1.0000, 0.5267, 0.8316, 0.4067, 0.3826]])


Now let us look at what happens when you take out $\phi$, i.e. take out the RMSNorm

In [ ]:
# Taking out RMSNorm and seeing probabilites with random activation of each neuron (column) of W_out
logits = U @ w_out @ x
probabilites = softmax(logits)
print("Normal Activations:")
print(probabilites)

print("\n--------------------------------\n")

# Now let us scale up the activation (x[0]) for the first column of W_out (representing our entropy neuron) and see the effect
x[0] *= 10
logits = U @ w_out @ x
probabilites_scaled = softmax(logits)
print("Scaled Entropy Neuron Activation:")
print(probabilites_scaled)

Normal Activations:
tensor([0.3077, 0.1543, 0.0305, 0.1216, 0.0603, 0.1004, 0.1201, 0.0335, 0.0717])

--------------------------------

Scaled Entropy Neuron Activation
tensor([0.3077, 0.1543, 0.0305, 0.1216, 0.0603, 0.1004, 0.1201, 0.0335, 0.0717])


Notice the probability distributions are identical. This is caused by what what explained in the first section, shifting logits doesn't effect the softmax output

Next, let us add back in the RMSNorm and try this again (keep everything else the same):

In [22]:
# perform the exact same initializations as above (same code without print statements)
w_out = (torch.rand((5,9)) )
U = ( torch.rand((9,5)) ) 
x = torch.rand(9)
w_out.T[0] = torch.zeros(5)
w_out[0][0] = torch.ones(1)
U.T[0] = torch.ones(9) 

# perform the same sequence but add in the RMSNorm
logits = U @ RMS(w_out @ x)
probabilites = softmax(logits)
print("Normal Activations:")
print(probabilites, "\n")

print("\n--------------------------------\n")

# Now let us scale up the activation (x[0]) for the first column of W_out (representing our entropy neuron) and see the effect
x[0] *= 10
logits = U @ RMS(w_out @ x)
probabilites_scaled = softmax(logits)
print("Scaled Entropy Neuron Activation:")
print(probabilites_scaled)

Normal Activations:
tensor([0.1191, 0.3058, 0.0479, 0.1457, 0.0401, 0.0570, 0.1429, 0.1112, 0.0301]) 


--------------------------------

Scaled Entropy Neuron Activation:
tensor([0.1215, 0.1811, 0.0825, 0.1323, 0.0766, 0.0889, 0.1312, 0.1180, 0.0679])


Adding in RMSNorm, you can see that the probability distribution did change this time. What is happening here is although the logits are still being shifted the same, this shift does impact the RMSNorm in that when adding the sum of the sqaured values, each squared value obviously doesn't increase linearly as they are shifted. This non-linear increase in the sum compared to a linear increase in the shift creates a heavier and heavier proportional normalization factor. And this acts just like changing the tempature in a softmax. As a result you can see that all ordering of the probabilites are preserved (just like tempature)"

In [23]:

print("This is showing the top 5 probabilites with their respective indexes (second list):\n")

print("Normal Activations")
print(torch.topk(probabilites, 5))

print("\n--------------------------------\n")

print("Scaled Entropy Neuron Activation:")
print(torch.topk(probabilites_scaled, 5))

This is showing the top 5 probabilites with their respective indexes (second list):

Normal Activations
torch.return_types.topk(
values=tensor([0.3058, 0.1457, 0.1429, 0.1191, 0.1112]),
indices=tensor([1, 3, 6, 0, 7]))

--------------------------------

Scaled Entropy Neuron Activation:
torch.return_types.topk(
values=tensor([0.1811, 0.1323, 0.1312, 0.1215, 0.1180]),
indices=tensor([1, 3, 6, 0, 7]))


## Identification of these Entropy Neurons in a Llama 3.1 8B model

### Setup and Helper Functions

Set up packages, authentification and high level variables.

In [26]:
# import necessary libraries
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig
from huggingface_hub import login
import numpy as np
import matplotlib.pyplot as plt

# Llama models require premission to access their models - log into huggingface
your_token = "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" # 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
login(token=your_token)


Create a Helper class that will abstract out some of the implementation details and make use of resuable code

In [27]:
class Helper():
    """
    A helper class that will define typical methods that will be used for each implementation or identification
    of Entropy Neurons and their use cases
    """

    # Define attributes (I obtained this by inspecting the layers of the model)
    model_name = "meta-llama/Llama-3.1-8B" # Name of model being used
    layer_index = 31 # Last transformer layer
    wout_matrix_key = f"model.layers.{layer_index}.mlp.down_proj.weight" # key for getting W_out matrix
    unembedding_matrix_key = f"lm_head.weight" # key for getting unembedding matrix

    def get_state_dict_matrix(self, state_dict, key):
        # Obtain the w_out matrix (last weight matrix before layer norm in last transformer block)
        if key in state_dict:
            matrix = state_dict[key]
        else:
            print(f"\n{key} not found. Check the exact layer naming in the state_dict keys.")
        return matrix

    def get_unembed_and_wout_matrices(self):
        # load in the model
        model = AutoModelForCausalLM.from_pretrained(
            self.model_name,
            torch_dtype=torch.float32,  # use float32 for analysis
            device_map="cpu",
        )
        # Retreive the state dictionary needed to get weight matrices
        state_dict = model.state_dict()
        W_out = self.get_state_dict_matrix(state_dict, self.wout_matrix_key)
        U = self.get_state_dict_matrix(state_dict, self.unembedding_matrix_key)
        return U, W_out
        

### Reproducing Confidence Regulation Neurons in Language Models Procedure

This approach will be following the identification approach in the paper: Confidence Regulation Neurons in Language Models

First let us retrieve the Unembedding matrix, U, and last projection matrix in the last transformer layer, W_out:

In [29]:
# Helper class will get this for us
helper = Helper()
# get the respective weight matrices
U, W_out = helper.get_unembed_and_wout_matrices()
# Inspect the shape of these matrices:
print(f'The shape of the Unembedding matrix: {U.shape}')
print(f'The shape of the W_out matrix: {W_out.shape}')

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

The shape of the Unembedding matrix: torch.Size([128256, 4096])
The shape of the W_out matrix: torch.Size([4096, 14336])


Entropy Neurons, are columns in the W_out matrix that have a the unique effect of either not effecting or shifting the logits. We can see their effect directly by computing $W_u W_{out} = L$. Each column in L shows the effect that each column of W_out has on the logits (with an activation value of 1). This is often refered to as logit attribution

In [30]:
# Find the logit attribution (this is projecting the columns of w_out to vocab space or finding effect of neuron on logits)
L = U @ W_out # matmult of W_u @ w_out
print(f'The shape of L: {L.shape}')
print(f'The first column of L: {L[0]}')

The shape of L: torch.Size([128256, 14336])
The first column of L: tensor([-0.0034,  0.0053,  0.0071,  ..., -0.0024, -0.0037, -0.0030])


The paper identifies Entropy based on two metrics. The first is the normalized variance of the logit attribution (normalized variance of column i in $L$, is for neuron i). The normalization factor they use is $||U||_{dim=1} ||w_{out}||$ where $w_{out}$ is the ith column in $W_{out}$ and $||U||_{dim=1}$ is the Norms column-wise. This normalization factor maps each individual index of $W_u w_{out}$ to the cosine similarity between $w_{out}$ and the respective row of $W_u$. Having a constant (low variance) cosine similarity could be interpreted as: the added effect toward the logits this neuron has doesn't even "consider" at which token it is, just blindly contributes. I do have reservations about why this is the correct approach as a constant cosine similarity >0 wouldn't necessarly shift the logits as it would increase the logits of each token proportion to the norm over each row. However, the paper does talk about how these are typically in the null space of $W_u$ which means that this effectivly doesn't matter (cosine simularity of 0).

On a side note I would like to add that in the paper they have $W_u \in \mathbb{R^{|v| \times d_{model}}}$ and say $||W_u||_{dim=1}$ which would be the norm over the rows but also say this is the column norm. This has been very confusing for me and seems contradictory.

In [ ]:
# Compute normilization factor ||W_u||_dim1. I am setting keepdim = True to pad for matrix multiplication
unembed_column_norm = U.norm(dim=1, keepdim=True)
print(f'The shape of the row norms of U: {unembed_column_norm.shape}')

# Calculate the norm of each column in W_out
W_out_norm = W_out.norm(dim=0, keepdim=True)

print(f'The shape of the column norms of W_out: {W_out_norm.shape}')

print("\n--------------------------------\n")
# We can calculate the normilzation factor for each column in W_out by taking the matrix multiplicaton.
# This is the outer product of two vectors. The ith column in the output of this outer product is the 
# norm vector of U times the ith value in norm vector for W_out. exactly what we want for ith neuron
norm_values = unembed_column_norm @ W_out_norm
print(f'The shape of the normilization factor matrix: {norm_values.shape}')

The shape of the row norms of U: torch.Size([128256, 1])
The shape of the column norms of W_out: torch.Size([1, 14336])

--------------------------------

The shape of the normilization factor matrix: torch.Size([128256, 14336])


So what happens here is we will take one column of the logit attribution representing the effect of a neuron on the logits. This is of dim = |tokens|. A column in our normilization factor matrix is also of dim = |tokens|. We will do a element-wise division which gives us the correct normilization presented in the paper (I believe lol).

In [ ]:
# Here are the normalized logit attributions (W_u w_out / ||W_u||_dim=1 ||w_out||) which acts as the cosine similarity
L_norm = torch.div(L, norm_values)
print(L_norm.shape)
print(L_norm[0])

# We dont need norm vectors or original L anymore and are quite large and take up memory
del W_out_norm
del unembed_column_norm
del norm_values
del L

torch.Size([128256, 14336])
tensor([-0.0035,  0.0068,  0.0090,  ..., -0.0028, -0.0046, -0.0056])
